name: Devyce Daily Scraper

on:
  schedule:
    - cron: '0 22 * * 1-5'  # 11PM UK time (22:00 UTC), Mon–Fri
  workflow_dispatch:

jobs:
  scrape-and-archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Ensure weekly-data directory exists
        run: mkdir -p weekly-data && touch weekly-data/.gitkeep

      - name: Run scraper
        env:
          DEVYCE_EMAIL: ${{ secrets.DEVYCE_EMAIL }}
          DEVYCE_PASSWORD: ${{ secrets.DEVYCE_PASSWORD }}
        run: node devyce-scraper.js

      - name: Run weekly archiver
        run: node archive-summary.js

      - name: Deploy JSON outputs to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: . # Everything in root (including *.json and /weekly-data)
          clean: false
          single-commit: true
