name: Devyce Scraper

on:
  schedule:
    - cron: "*/10 8-16 * * 1-5"     # Every 10 mins from 9am-5pm UK (Mon-Fri)
    - cron: "0 22 * * 1-5"          # 11pm UK (archive run, Mon-Fri)
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node devyce-scraper.js
        env:
          DEVYCE_EMAIL: ${{ secrets.DEVYCE_EMAIL }}
          DEVYCE_PASSWORD: ${{ secrets.DEVYCE_PASSWORD }}

      - name: Prepare output
        run: |
          mkdir output
          cp call-stats.json output/

          node archive-summary.js

          cp weekly-summary.json output/
          cp index.html output/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          publish_branch: gh-pages
